### PR TITLE
Do more with even less code!

### PR DESCRIPTION
**Pull request by SniverDaBest**
Changes I made:
- Removed variables that were only used once, and just put them into the `if` statements themselves.
- Got rid of the `for` loop, and optimized the `if` statement.

### CODE REVIEW

**Comment by SniverDaBest** [comment]
Well it's not more, but it's still a bit less code.

**Comment by FloppyMacguffum** [comment]
There's not really any real optimizations I noticed.
I tested both of these scripts with Python 3.9.6 multiple times.
Here's some sample results:
```
Sniver's implementation
real	0m0.017s
user	0m0.013s
sys	0m0.004s
Floppy's implementation
real	0m0.012s
user	0m0.008s
sys	0m0.004s
```
I got these results using securly's crxs from [extensions.securly.com/extensions.xml](https://extensions.securly.com/extensions.xml) and put the testing code into a shell script to test the speeds of our code:
```
time crxtoziptests/sniverdabest/crxtozip/crxtozip.py ~/crextn_client_MV3_2.98.0.0.crx crxtoziptests/sniverdabest/crxtozip/securlysux.crx
time crxtoziptests/floppymacguffum/crxtozip/crxtozip.py ~/crextn_client_MV3_2.98.0.0.crx crxtoziptests/floppymacguffum/crxtozip/securlysux.crx
```
While both of our scripts sometimes output the same results when run with the time command, mine generally seems to be faster from my testing. Of course Python 3.9.6 is old and your script might perform better on other versions of Python.

**Comment by SniverDaBest** [comment]
I've noticed that they both run at ~0.40ms. I haven't seen much of a fluctuation either, so I really couldn't tell you. I guess this pull request should be closed then.

**Comment by FloppyMacguffum** [comment]
Did you even test your code? I can't extract a single crx file. There's also some other issues I noticed too...........

**Comment by FloppyMacguffum** [comment]
Sorry I accidentally tested the wrong versions.

**Comment by FloppyMacguffum** [comment]
But your code can't extract a convert a crx file to a zip though.

**Comment by SniverDaBest** [comment]
Yeah I did test it. I was working w/ a dark reader download from CRYoink.

**Comment by FloppyMacguffum** [comment]
I tried extracting securly's crx's, ublock, and a bunch of other things but none of them worked.......

**Comment by SniverDaBest** [comment]
Weird. I even tested uBlock Origin...

**Comment by FloppyMacguffum** [comment]
Run a quick ls -lah, shasum, and diff on my code and your code. Are you sure you're not using my code by accident?

**Pull request closed without merging**
